modLoader="javafml"
loaderVersion="[35,)"
license="Academic Free License v3.0"

[[mods]]
modId="googlymod"
version="0.0.4"
displayName="The Googly Mod"
credits="The wondrous mod of the wondrous Googly Realm. Tread carefully."
displayURL="https://mcreator.net"
authors="Icarus404, MCreator"
description='''
The Googly Realm
'''

[[dependencies.googlymod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4]"
    ordering="NONE"
    side="BOTH"




